/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Student;
import javax.swing.JOptionPane;

public class App {
   

    public static void main(String[] args) {
       String StudentNumber;
       String Name;
       String Surname;
       String Email;
       int PhoneNumber;
       int Test1;
       int Test2;
       int Assignment;
       double DPMarks;
       double FinalMarks;
               
    }
}
